// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBk1zhi-MLBO9WUtgakUn1swcSdiXnHpC0',
    appId: '1:949202628472:web:9490e7663cbc222ba3228d',
    messagingSenderId: '949202628472',
    projectId: 'fresh-bp',
    authDomain: 'fresh-bp.firebaseapp.com',
    storageBucket: 'fresh-bp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuh4v0XBe8KFjWMta1MuwQ6yP9QJyw-f0',
    appId: '1:949202628472:android:91bbb219319d0c0aa3228d',
    messagingSenderId: '949202628472',
    projectId: 'fresh-bp',
    storageBucket: 'fresh-bp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFGNydqjkNqB4pgTHFmRUoxZNo9DHR_VM',
    appId: '1:949202628472:ios:38232cadc3b8d2dda3228d',
    messagingSenderId: '949202628472',
    projectId: 'fresh-bp',
    storageBucket: 'fresh-bp.appspot.com',
    iosBundleId: 'com.example.freshh',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFGNydqjkNqB4pgTHFmRUoxZNo9DHR_VM',
    appId: '1:949202628472:ios:38232cadc3b8d2dda3228d',
    messagingSenderId: '949202628472',
    projectId: 'fresh-bp',
    storageBucket: 'fresh-bp.appspot.com',
    iosBundleId: 'com.example.freshh',
  );
}
